import type { ComparisonSupplier } from "../../lib/api/compareQuotes";
import { formatMoney } from "../workflow/formatters";
import { CostComposition } from "./CostComposition";
import { VisualizationSelector } from "./VisualizationSelector";
import { supplierDisplayName } from "./comparisonDisplay";
import { VIEW_OPTIONS, VisualizationViews } from "./visualizationConfig";

const colors = ["bg-[#0007cd]", "bg-[#666666]", "bg-[#333333]"];
const labels = ["품목금액", "운송비", "부가세"];

export function CostCompositionVisualization({ suppliers, view, onChange }: { suppliers: ComparisonSupplier[]; view: VisualizationViews["costComposition"]; onChange: (view: VisualizationViews["costComposition"]) => void }) {
  const selector = <VisualizationSelector label="비용 구성" onChange={onChange} options={VIEW_OPTIONS.costComposition} value={view} />;
  if (view === "stacked-bar") return <CostComposition headerAction={selector} suppliers={suppliers} />;
  const maxPart = Math.max(0, ...suppliers.flatMap((supplier) => [supplier.subtotal ?? 0, supplier.shippingCost ?? 0, supplier.vat ?? 0]));
  return <section className="rounded-md border border-line bg-white p-5"><header className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-[17px] font-semibold text-text">비용 구성</h2><p className="mt-1 text-[13px] text-muted">품목금액·운송비·부가세의 구성입니다.</p></div>{selector}</header>
    {view === "table" ? <div className="data-scroll mt-4"><table className="w-full min-w-[650px]"><thead><tr>{["공급업체", "품목금액", "운송비", "부가세", "최종금액"].map((label, index) => <th className={index === 0 ? "text-left" : "text-right"} key={label} scope="col">{label}</th>)}</tr></thead><tbody>{suppliers.map((supplier) => <tr key={supplier.savedName}><th className="text-left font-semibold" scope="row">{supplierDisplayName(supplier)}</th><td className="text-right tabular-nums">{formatMoney(supplier.subtotal)}</td><td className="text-right tabular-nums">{supplier.shippingIncluded ? "포함" : formatMoney(supplier.shippingCost)}</td><td className="text-right tabular-nums">{formatMoney(supplier.vat)}</td><td className="text-right font-semibold tabular-nums">{formatMoney(supplier.grandTotal)}</td></tr>)}</tbody></table></div> : <div className="mt-4 divide-y divide-line border-y border-line">{suppliers.map((supplier) => { const parts = [supplier.subtotal, supplier.shippingCost, supplier.vat]; const totalParts = parts.reduce<number>((sum, value) => sum + (value ?? 0), 0); return <article className="grid gap-3 py-4 lg:grid-cols-[14rem_1fr_9rem] lg:items-center" key={supplier.savedName}><h3 className="text-sm font-semibold">{supplierDisplayName(supplier)}</h3>{view === "ratio-bar" ? <div className={`flex h-6 overflow-hidden bg-[#eef0f3] ${supplier.status === "conditional" ? "border border-dashed border-[#aeb7c2]" : ""}`}>{parts.map((part, index) => part !== null && part > 0 ? <span aria-label={`${labels[index]} ${formatMoney(part)}`} className={colors[index]} key={labels[index]} style={{ width: `${totalParts ? part / totalParts * 100 : 0}%` }} tabIndex={0} /> : null)}</div> : <div className="grid grid-cols-3 gap-3">{parts.map((part, index) => <div className="grid grid-cols-[5rem_1fr] items-center gap-2" key={labels[index]}><span className="text-xs text-muted">{labels[index]}</span><div className="h-3 bg-[#eef0f3]"><span className={`block h-full ${colors[index]}`} style={{ width: `${part !== null && maxPart ? Math.max(3, part / maxPart * 100) : 0}%` }} /></div></div>)}</div>}<span className="text-right text-sm font-semibold tabular-nums">{formatMoney(supplier.grandTotal)}</span></article>; })}<div className="flex flex-wrap gap-4 py-3 text-xs text-muted">{labels.map((label, index) => <span className="flex items-center gap-2" key={label}><i className={`h-3 w-3 ${colors[index]}`} />{label}</span>)}</div></div>}
  </section>;
}
