import type { ComparisonItemGroup, ComparisonOffer, ComparisonSupplier } from "../../lib/api/compareQuotes";
import { formatMoney } from "../workflow/formatters";
import { ItemPriceTable } from "./ItemPriceTable";
import { VisualizationSelector } from "./VisualizationSelector";
import { statusLabel } from "./comparisonDisplay";
import { VIEW_OPTIONS, VisualizationViews } from "./visualizationConfig";

function priceHeat(offer: ComparisonOffer | undefined, offers: ComparisonOffer[]) {
  if (!offer || offer.unitPrice === null || offer.status !== "comparable") return "bg-[#f8f9fb]";
  const prices = offers.filter((entry) => entry.status === "comparable" && entry.unitPrice !== null).map((entry) => entry.unitPrice as number);
  const min = Math.min(...prices); const max = Math.max(...prices); const ratio = max === min ? 0 : (offer.unitPrice - min) / (max - min);
  return ratio < .34 ? "bg-[#edf5f0]" : ratio < .67 ? "bg-[#f3f4f6]" : "bg-[#f9efee]";
}

export function ItemPriceVisualization({ groups, suppliers, view, onChange }: { groups: ComparisonItemGroup[]; suppliers: ComparisonSupplier[]; view: VisualizationViews["itemPrice"]; onChange: (view: VisualizationViews["itemPrice"]) => void }) {
  const selector = <VisualizationSelector label="품목별 단가 비교" onChange={onChange} options={VIEW_OPTIONS.itemPrice} value={view} />;
  if (view === "table") return <ItemPriceTable groups={groups} headerAction={selector} suppliers={suppliers} />;
  const supplierNames = new Map(suppliers.map((supplier) => [supplier.savedName, supplier.supplierName ?? supplier.originalName]));
  const maxPrice = Math.max(0, ...groups.flatMap((group) => group.offers.map((offer) => offer.unitPrice ?? 0)));
  return <section className="rounded-md border border-line bg-white p-5"><header className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-[17px] font-semibold text-text">품목별 단가 비교</h2><p className="mt-1 text-[13px] text-muted">가격 적용 조건과 품목별 단가 차이를 함께 확인합니다.</p></div>{selector}</header>
    {view === "heatmap" ? <div className="data-scroll mt-4"><table className="w-full min-w-[700px]"><thead><tr><th className="text-left" scope="col">품목</th>{suppliers.map((supplier) => <th className="text-right" key={supplier.savedName} scope="col">{supplier.supplierName ?? supplier.originalName}</th>)}</tr></thead><tbody>{groups.map((group) => <tr key={group.normalizedItemName}><th className="text-left font-semibold" scope="row">{group.normalizedItemName}</th>{suppliers.map((supplier) => { const offer = group.offers.find((entry) => entry.savedName === supplier.savedName); return <td className={`text-right font-medium tabular-nums ${priceHeat(offer, group.offers)}`} key={supplier.savedName}>{!offer ? "미제안" : offer.unitPrice === null ? "확인 필요" : <>{formatMoney(offer.unitPrice)}{offer.status === "conditional" && <span className="ml-2 whitespace-nowrap text-xs font-normal text-warning">● 조건 확인</span>}</>}</td>; })}</tr>)}</tbody></table></div> :
    view === "grouped-bar" ? <div className="mt-5 flex min-h-64 gap-8 overflow-x-auto border-b border-[#aeb7c2] px-4">{groups.map((group) => <article className="flex min-w-72 flex-1 flex-col justify-end" key={group.normalizedItemName}><div className="flex h-48 items-end justify-center gap-3">{group.offers.map((offer) => { const conditional = offer.status === "conditional"; return <div className="flex h-full w-16 flex-col justify-end text-center" key={offer.savedName}><span className="mb-2 text-xs font-semibold tabular-nums">{formatMoney(offer.unitPrice)}</span>{offer.unitPrice !== null && <div className={`mx-auto w-10 ${conditional ? "border border-dashed border-[#aeb7c2] bg-[#d7dce2]" : "bg-[#264b73]"}`} style={{ height: `${maxPrice ? Math.max(4, offer.unitPrice / maxPrice * 100) : 0}%` }} tabIndex={0} title={`${supplierNames.get(offer.savedName)} · ${statusLabel[offer.status]}`} />}<span className={`mt-1 truncate text-xs ${conditional ? "text-warning" : "text-muted"}`}>{supplierNames.get(offer.savedName)}</span></div>; })}</div><h3 className="py-3 text-center text-sm font-semibold">{group.normalizedItemName}</h3></article>)}</div> :
    <div className="mt-5 space-y-7">{groups.map((group) => <article key={group.normalizedItemName}><div className="flex justify-between"><h3 className="text-sm font-semibold">{group.normalizedItemName}</h3><span className="text-[13px] text-muted">비교 기준 {formatMoney(group.benchmarkUnitPrice)}</span></div><div className="relative mt-4 h-10 border-y border-line">{group.benchmarkUnitPrice !== null && <span aria-label={`기준 단가 ${formatMoney(group.benchmarkUnitPrice)}`} className="absolute inset-y-0 w-px bg-brand" style={{ left: `${maxPrice ? group.benchmarkUnitPrice / maxPrice * 100 : 0}%` }} title="비교 기준 단가" />}{group.offers.map((offer, index) => offer.unitPrice === null ? null : <button aria-label={`${supplierNames.get(offer.savedName)} ${formatMoney(offer.unitPrice)} ${statusLabel[offer.status]}`} className={`absolute h-4 w-4 -translate-x-1/2 rounded-full ${offer.status === "conditional" ? "border-2 border-[#8a4b08] bg-white" : "bg-[#264b73]"}`} key={offer.savedName} style={{ left: `${maxPrice ? offer.unitPrice / maxPrice * 100 : 0}%`, top: `${4 + index * 6}px` }} title={offer.status === "conditional" ? "조건 확인 필요 · MOQ 조건 확인" : supplierNames.get(offer.savedName)} type="button" />)}</div><div className="mt-2 flex flex-wrap gap-3 text-xs text-muted">{group.offers.map((offer) => <span key={offer.savedName}>{supplierNames.get(offer.savedName)} {formatMoney(offer.unitPrice)}</span>)}</div></article>)}</div>}
  </section>;
}

