import type { ReactNode } from "react";
import type { ComparisonItemGroup, ComparisonSupplier } from "../../lib/api/compareQuotes";
import { displayValue, formatBenchmarkDifference, formatMoney, formatMoqResult } from "../workflow/formatters";
import { statusLabel, statusStyle } from "./comparisonDisplay";

export function ItemPriceTable({ groups, suppliers, headerAction }: { groups: ComparisonItemGroup[]; suppliers: ComparisonSupplier[]; headerAction?: ReactNode }) {
  const names = new Map(suppliers.map((supplier) => [supplier.savedName, supplier.supplierName ?? supplier.originalName]));
  return <section className="rounded-md border border-line bg-white p-5"><header className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-[17px] font-semibold text-text">품목별 단가 비교</h2><p className="mt-1 text-[13px] text-muted">MOQ 충족 여부와 단가 차이를 품목별로 확인합니다.</p></div>{headerAction}</header><div className="mt-4 space-y-6">{groups.length === 0 && <p className="bg-surface-alt p-3 text-[13px] text-muted">필터 조건에 해당하는 품목이 없습니다.</p>}{groups.map((group) => <article key={group.normalizedItemName}><div className="mb-3 flex flex-wrap items-end justify-between gap-2"><div><h3 className="text-sm font-semibold text-text">{group.normalizedItemName}</h3><p className="text-[13px] text-muted">비교 기준 단가 {formatMoney(group.benchmarkUnitPrice)}</p></div><span className={`status-badge ${statusStyle[group.comparisonStatus]}`}>{statusLabel[group.comparisonStatus]}</span></div><div className="data-scroll"><table className="w-full min-w-[1050px]"><thead><tr>{["공급업체", "원본 품목명", "규격", "수량", "단위", "단가", "품목 금액", "MOQ", "충족 여부", "기준 대비", "상태"].map((label) => <th className={["수량", "단가", "품목 금액", "MOQ", "기준 대비"].includes(label) ? "text-right" : "text-left"} key={label}>{label}</th>)}</tr></thead><tbody>{group.offers.filter((offer) => names.has(offer.savedName)).map((offer) => <tr key={offer.savedName}><td className="font-semibold">{names.get(offer.savedName)}</td><td>{displayValue(offer.originalItemName)}</td><td>{displayValue(offer.specification)}</td><td className="text-right">{displayValue(offer.quantity)}</td><td>{displayValue(offer.unit)}</td><td className="text-right tabular-nums">{formatMoney(offer.unitPrice)}</td><td className="text-right tabular-nums">{formatMoney(offer.amount)}</td><td className="text-right">{displayValue(offer.moqQuantity)}</td><td>{formatMoqResult(offer)}</td><td className="text-right">{formatBenchmarkDifference(offer.status, offer.differenceFromBenchmark, offer.differenceRate)}</td><td><span className={`status-badge whitespace-nowrap ${statusStyle[offer.status]}`}>{offer.moqMet === false ? "MOQ 미충족" : statusLabel[offer.status]}</span></td></tr>)}</tbody></table></div></article>)}</div></section>;
}

