import type { ComparisonSupplier } from "../../lib/api/compareQuotes";
import { displayValue } from "../workflow/formatters";
import { VisualizationSelector } from "./VisualizationSelector";
import { statusLabel, supplierDisplayName } from "./comparisonDisplay";
import { VIEW_OPTIONS, VisualizationViews } from "./visualizationConfig";

export function LeadTimeVisualization({ suppliers, shortestLead, view, onChange }: { suppliers: ComparisonSupplier[]; shortestLead: number | null; view: VisualizationViews["leadTime"]; onChange: (view: VisualizationViews["leadTime"]) => void }) {
  const maximum = Math.max(0, ...suppliers.map((supplier) => supplier.leadTimeDays ?? 0));
  const selector = <VisualizationSelector label="납기 비교" onChange={onChange} options={VIEW_OPTIONS.leadTime} value={view} />;
  return <section className="rounded-md border border-line bg-white p-5"><header className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-[17px] font-semibold text-text">납기 비교</h2><p className="mt-1 text-[13px] text-muted">숫자로 확인된 납기를 같은 기준으로 비교합니다.</p></div>{selector}</header>
    {view === "table" ? <div className="data-scroll mt-4"><table className="w-full"><thead><tr><th className="text-left" scope="col">공급업체</th><th className="text-left" scope="col">상태</th><th className="text-right" scope="col">납기</th></tr></thead><tbody>{suppliers.map((supplier) => <tr key={supplier.savedName}><th className="text-left font-semibold" scope="row">{supplierDisplayName(supplier)}</th><td>{statusLabel[supplier.status]}</td><td className="text-right tabular-nums">{supplier.leadTimeDays === null ? displayValue(supplier.leadTime) : `${supplier.leadTimeDays}일${supplier.leadTimeDays === shortestLead ? " · 최단 납기" : ""}`}</td></tr>)}</tbody></table></div> :
    view === "vertical-bar" ? <div className="mt-5 flex h-52 items-end gap-5 overflow-x-auto border-b border-[#aeb7c2] px-4">{suppliers.map((supplier) => { const conditional = supplier.status === "conditional"; return <div className="flex h-full min-w-28 flex-1 flex-col justify-end text-center" key={supplier.savedName}>{supplier.leadTimeDays === null ? <p className="mb-4 text-xs text-muted">{displayValue(supplier.leadTime)}</p> : <><span className="mb-2 text-[13px] font-semibold tabular-nums">{supplier.leadTimeDays}일</span><div className={`mx-auto w-14 ${conditional ? "border border-dashed border-[#aeb7c2] bg-[#d7dce2]" : "bg-[#264b73]"}`} style={{ height: `${maximum ? Math.max(5, supplier.leadTimeDays / maximum * 100) : 0}%` }} tabIndex={0} title={supplier.leadTimeDays === shortestLead ? "최단 납기" : statusLabel[supplier.status]} /></>}<p className="mt-2 text-xs font-medium">{supplierDisplayName(supplier)}</p>{conditional && <span className="text-xs text-warning">● 조건 확인</span>}</div>; })}</div> :
    view === "horizontal-bar" ? <div className="mt-4 divide-y divide-line">{suppliers.map((supplier) => { const days = supplier.leadTimeDays; const conditional = supplier.status === "conditional"; return <article className="grid gap-2 py-4 sm:grid-cols-[14rem_1fr_6rem] sm:items-center" key={supplier.savedName}><div><h3 className="text-sm font-semibold">{supplierDisplayName(supplier)}</h3>{conditional && <span className="text-xs text-warning">● 조건 확인</span>}</div>{days === null ? <p className="text-[13px] text-muted">일수 확인 필요</p> : <div className={`h-3 bg-[#eef0f3] ${conditional ? "border border-dashed border-[#aeb7c2]" : ""}`}><div className={`h-full ${conditional ? "bg-[#d7dce2]" : "bg-[#264b73]"}`} style={{ width: `${maximum ? Math.max(4, days / maximum * 100) : 0}%` }} /></div>}<p className="text-right text-sm font-semibold tabular-nums">{days === null ? displayValue(supplier.leadTime) : `${days}일`}</p></article>; })}</div> :
    <div className="mt-5 space-y-5">{suppliers.map((supplier) => <div key={supplier.savedName}><div className="flex justify-between text-sm"><span className="font-semibold">{supplierDisplayName(supplier)}</span><span className="font-semibold tabular-nums">{supplier.leadTimeDays === null ? displayValue(supplier.leadTime) : `${supplier.leadTimeDays}일`}</span></div>{supplier.leadTimeDays === null ? <p className="mt-2 text-xs text-muted">그래프 제외 · 원문 조건 확인</p> : <div className="relative mt-3 h-6 border-y border-line"><button aria-label={`${supplierDisplayName(supplier)} 납기 ${supplier.leadTimeDays}일`} className={`absolute top-1/2 h-4 w-4 -translate-x-1/2 -translate-y-1/2 rounded-full ${supplier.status === "conditional" ? "border-2 border-[#8a4b08] bg-white" : "bg-[#264b73]"}`} style={{ left: `${maximum ? supplier.leadTimeDays / maximum * 100 : 0}%` }} title={supplier.leadTimeDays === shortestLead ? "최단 납기" : statusLabel[supplier.status]} type="button" /></div>}</div>)}</div>}
  </section>;
}

