import type { ReactNode } from "react";
import type { ComparisonSupplier } from "../../lib/api/compareQuotes";
import { displayValue, formatBenchmarkDifference, formatMoney, formatShipping } from "../workflow/formatters";
import { statusLabel, statusStyle, supplierDisplayName } from "./comparisonDisplay";

export function SupplierComparisonTable({ suppliers, benchmark, headerAction }: { suppliers: ComparisonSupplier[]; benchmark: number | null; headerAction?: ReactNode }) {
  const rows: Array<{ label: string; numeric?: boolean; value: (supplier: ComparisonSupplier) => string }> = [
    { label: "품목금액", numeric: true, value: (supplier) => formatMoney(supplier.subtotal) }, { label: "운송비", numeric: true, value: formatShipping }, { label: "부가세", numeric: true, value: (supplier) => formatMoney(supplier.vat) }, { label: "최종금액", numeric: true, value: (supplier) => formatMoney(supplier.grandTotal) },
    { label: "기준 대비", numeric: true, value: (supplier) => formatBenchmarkDifference(supplier.status, supplier.differenceFromBenchmark, supplier.differenceRate) }, { label: "납기", value: (supplier) => supplier.leadTimeDays === null ? displayValue(supplier.leadTime) : `${supplier.leadTimeDays}일` }, { label: "MOQ", value: (supplier) => displayValue(supplier.moq) }, { label: "결제조건", value: (supplier) => displayValue(supplier.paymentTerms) }, { label: "유효기간", value: (supplier) => displayValue(supplier.validity) },
  ];
  return <section className="rounded-md border border-line bg-white p-5"><header className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-[17px] font-semibold text-text">공급업체 종합 비교</h2><p className="mt-1 text-[13px] text-muted">금액과 주요 거래조건을 공급업체별로 확인합니다.</p></div>{headerAction}</header><div className="data-scroll mt-4"><table className="w-full min-w-[900px] border-collapse"><thead><tr><th className="sticky left-0 top-0 z-20 min-w-40 bg-[#f3f4f6] text-left">비교 항목</th>{suppliers.map((supplier) => <th className="sticky top-0 z-10 min-w-56 bg-[#f3f4f6] text-left" key={supplier.savedName}><span>{supplierDisplayName(supplier)}</span>{supplier.status === "comparable" && supplier.grandTotal === benchmark && <span className="ml-2 text-xs font-medium text-brand">비교 기준</span>}</th>)}</tr></thead><tbody><tr><th className="sticky left-0 bg-white text-left font-semibold">비교 상태</th>{suppliers.map((supplier) => <td key={supplier.savedName}><span className={`status-badge ${statusStyle[supplier.status]}`}>{statusLabel[supplier.status]}</span></td>)}</tr>{rows.map((row) => <tr key={row.label}><th className="sticky left-0 bg-white text-left font-semibold">{row.label}</th>{suppliers.map((supplier) => <td className={row.numeric ? "text-right tabular-nums" : "text-left"} key={supplier.savedName}>{row.value(supplier)}</td>)}</tr>)}</tbody></table></div>{suppliers.length === 0 && <p className="mt-4 text-[13px] text-muted">필터 조건에 해당하는 공급업체가 없습니다.</p>}</section>;
}

