import type { ComparisonSupplier } from "../../lib/api/compareQuotes";
import { formatBenchmarkDifference, formatMoney } from "../workflow/formatters";
import { TotalCostChart } from "./TotalCostChart";
import { VisualizationSelector } from "./VisualizationSelector";
import { statusLabel, supplierDisplayName } from "./comparisonDisplay";
import { VIEW_OPTIONS, VisualizationViews } from "./visualizationConfig";

export function TotalCostVisualization({ suppliers, benchmark, view, onChange }: { suppliers: ComparisonSupplier[]; benchmark: number | null; view: VisualizationViews["totalCost"]; onChange: (view: VisualizationViews["totalCost"]) => void }) {
  const maximum = Math.max(0, ...suppliers.map((supplier) => supplier.grandTotal ?? 0));
  const selector = <VisualizationSelector label="총구매비용" onChange={onChange} options={VIEW_OPTIONS.totalCost} value={view} />;
  if (view === "horizontal-bar") return <TotalCostChart benchmark={benchmark} headerAction={selector} suppliers={suppliers} />;
  return <section className="rounded-md border border-line bg-white p-5"><header className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-[17px] font-semibold text-text">총구매비용 비교</h2><p className="mt-1 text-[13px] text-muted">업체별 견적금액과 가격 적용 조건을 비교합니다.</p></div>{selector}</header>
    {view === "table" ? <div className="data-scroll mt-4"><table className="w-full min-w-[700px]"><thead><tr>{["공급업체", "상태", "최종금액", "기준 대비", "차이율"].map((label) => <th className={label === "공급업체" || label === "상태" ? "text-left" : "text-right"} key={label} scope="col">{label}</th>)}</tr></thead><tbody>{suppliers.map((supplier) => <tr key={supplier.savedName}><th className="text-left font-semibold" scope="row">{supplierDisplayName(supplier)}</th><td>{statusLabel[supplier.status]}</td><td className="text-right font-semibold tabular-nums">{formatMoney(supplier.grandTotal)}</td><td className="text-right">{formatBenchmarkDifference(supplier.status, supplier.differenceFromBenchmark, supplier.differenceRate)}</td><td className="text-right">{supplier.differenceRate === null ? "확인 필요" : `${supplier.differenceRate.toFixed(2)}%`}</td></tr>)}</tbody></table></div> :
    view === "vertical-bar" ? <div className="mt-5 flex h-56 items-end gap-4 overflow-x-auto border-b border-[#aeb7c2] px-3">{suppliers.map((supplier) => { const height = supplier.grandTotal !== null && maximum ? Math.max(4, supplier.grandTotal / maximum * 100) : 0; const conditional = supplier.status === "conditional"; return <div className="flex h-full min-w-32 flex-1 flex-col justify-end text-center" key={supplier.savedName}><span className="mb-2 text-[13px] font-semibold tabular-nums">{formatMoney(supplier.grandTotal)}</span>{supplier.grandTotal !== null && <div className={`mx-auto w-16 ${conditional ? "border border-dashed border-[#aeb7c2] bg-[#d7dce2]" : "bg-[#264b73]"}`} style={{ height: `${height}%` }} tabIndex={0} title={`${statusLabel[supplier.status]} · ${formatBenchmarkDifference(supplier.status, supplier.differenceFromBenchmark, supplier.differenceRate)}`} />}<p className="mt-2 min-h-9 text-xs font-medium">{supplierDisplayName(supplier)}</p><span className={`text-xs ${conditional ? "text-warning" : "text-muted"}`}>{conditional ? "● 조건 확인" : supplier.grandTotal === benchmark ? "비교 기준" : statusLabel[supplier.status]}</span></div>; })}</div> :
    <div className="mt-5 space-y-5">{suppliers.map((supplier) => { const left = supplier.grandTotal !== null && maximum ? supplier.grandTotal / maximum * 100 : null; const conditional = supplier.status === "conditional"; return <div key={supplier.savedName}><div className="flex justify-between gap-3 text-sm"><span className="font-semibold">{supplierDisplayName(supplier)}</span><span className="font-semibold tabular-nums">{formatMoney(supplier.grandTotal)} · <span className="font-normal text-muted">{formatBenchmarkDifference(supplier.status, supplier.differenceFromBenchmark, supplier.differenceRate)}</span></span></div>{left === null ? <p className="mt-2 text-[13px] text-muted">금액 확인 필요</p> : <div className="relative mt-3 h-6 border-y border-line"><button aria-label={`${supplierDisplayName(supplier)} ${formatMoney(supplier.grandTotal)} ${statusLabel[supplier.status]}`} className={`absolute top-1/2 h-4 w-4 -translate-x-1/2 -translate-y-1/2 rounded-full ${conditional ? "border-2 border-[#8a4b08] bg-white" : "bg-[#264b73]"}`} style={{ left: `${left}%` }} title={supplier.warnings.join(" · ") || statusLabel[supplier.status]} type="button" /></div>}</div>; })}</div>}
  </section>;
}

